# Generated by Django 5.2.3 on 2025-07-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ipo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='drhp_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='rhp_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
