# Generated by Django 5.2.3 on 2025-07-23 01:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='drhp_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to_drhp),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='rhp_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to_rhp),
        ),
    ]
